// This file is generated by Slice Machine. Update with care!

import Benefits from './Benefits';
import Introduction from './Introduction';
import PlanDetails from './PlanDetails';
import PlansIntroduction from './PlansIntroduction';
import Service from './Service';
import Services from './Services';
import TitlePrimary from './TitlePrimary';

export {
	Benefits,
	Introduction,
	PlanDetails,
	PlansIntroduction,
	Service,
	Services,
	TitlePrimary,
};

export const components = {
	benefits: Benefits,
	introduction: Introduction,
	plan_details: PlanDetails,
	plans_introduction: PlansIntroduction,
	service: Service,
	services: Services,
	title_primary: TitlePrimary,
};
