// This file is generated by Slice Machine. Update with care!

import AboutContact from './AboutContact';
import AboutIntroduction from './AboutIntroduction';
import AboutTeams from './AboutTeams';
import Benefits from './Benefits';
import Introduction from './Introduction';
import Service from './Service';
import Services from './Services';
import TitlePrimary from './TitlePrimary';

export {
	AboutContact,
	AboutIntroduction,
	AboutTeams,
	Benefits,
	Introduction,
	Service,
	Services,
	TitlePrimary,
};

export const components = {
	about_contact: AboutContact,
	about_introduction: AboutIntroduction,
	about_teams: AboutTeams,
	benefits: Benefits,
	introduction: Introduction,
	service: Service,
	services: Services,
	title_primary: TitlePrimary,
};
