// This file is generated by Slice Machine. Update with care!

import Benefits from './Benefits';
import Introduction from './Introduction';
import Service from './Service';
import Services from './Services';
import TitlePrimary from './TitlePrimary';

export {
	Benefits,
	Introduction,
	Service,
	Services,
	TitlePrimary,
};

export const components = {
	benefits: Benefits,
	introduction: Introduction,
	service: Service,
	services: Services,
	title_primary: TitlePrimary,
};
